### ISSUE TITLE
IndexError: pop index out of range​

### ISSUE THREAD

**Issue by cjdunn** [roboDocs/CornerTools#2]
Using a simple shape like an /H I'm getting this error if I accidentally slide too far (in my example, when I go above 85 radius), and then the traceback wont go away and keeps printing if I change anything. 

Here's the full traceback: 
```
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 131, in callObserver_withMethod_forEvent_withInfo_
  File "cornerToolController.py", line 89, in setControls
  File "cornerToolController.py", line 121, in makePreviewGlyph
  File "cornerToolController.py", line 129, in makeCornerGlyph
  File "cornerToolController.py", line 157, in breakCorners
  File "/Users/cjdunn/Library/Application Support/RoboFont/plugins/CornerTools.roboFontExt/lib/glyphObjects.py", line 1502, in breakCorner
IndexError: pop index out of range​
```

Thanks! 

Example image: 
<img width="752" alt="corner_tools_error" src="https://user-images.githubusercontent.com/3900241/57255480-dd448e00-7021-11e9-956e-20f01eeadeb8.png">

Example glyph:
```
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="H" format="2">
  <advance width="450"/>
  <outline>
    <contour>
      <point x="53" y="0" type="line"/>
      <point x="136" y="0" type="line"/>
      <point x="136" y="366" type="line"/>
      <point x="314" y="366" type="line"/>
      <point x="314" y="0" type="line"/>
      <point x="397" y="0" type="line"/>
      <point x="397" y="750" type="line"/>
      <point x="314" y="750" type="line"/>
      <point x="314" y="439" type="line"/>
      <point x="136" y="439" type="line"/>
      <point x="136" y="750" type="line"/>
      <point x="53" y="750" type="line"/>
    </contour>
  </outline>
</glyph>
```

**Comment by typemytype** [comment]
could you test the GitHub version? and report back before pushing it to mechanic

thanks

**Comment by cjdunn** [comment]
Yes this works now, thank you!

**Comment by frankrolf** [comment]
This fix breaks the non-interactive corner rounding in the following way:
https://www.dropbox.com/s/7p2g739i9vt5i1f/corner.mov?dl=0

**Comment by ryanbugden** [comment]
I'd like to **bump** this ^

Corner points remain, and going back to previous version before #2 requires `ufoLib`
